version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: application:django
    container_name: app_container_django
    command: gunicorn MasterProject.wsgi:application --bind 0.0.0.0:8000