version: "3.8"
services:
  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    image: snapspeak-django:v1
    env_file:
      - .env
    ports:
      - ${DJANGO_PROD_PORT}:${DJANGO_EXPOSE_PORT}
    container_name: snapspeak_server
    command: sh -c "/django/docker-entrypoint.sh"
  
  mongodb:
    image: mongo:jammy
    container_name: snapspeak_mongodb
    ports:
      - ${MONGODB_PROD_PORT}:${MONGODB_EXPOSE_PORT}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: