version: "3.8"
services:
  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    image: snapspeak-django:v1
    env_file:
      - .env
    ports:
      - ${DJANGO_PROD_PORT}:${DJANGO_EXPOSE_PORT}
    container_name: snapspeak_server
    volumes:
      - staticfiles_vol:/django/staticfiles
    command: sh -c "/django/docker-entrypoint.sh"
  
  mongodb:
    image: mongo:jammy
    container_name: snapspeak_mongodb
    ports:
      - ${MONGODB_PROD_PORT}:${MONGODB_EXPOSE_PORT}
    volumes:
      - mongo_data:/data/db
  
  redis:
    image: redis:alpine
    container_name: snapspeak_redis
    ports:
      - ${REDIS_PROD_PORT}:${REDIS_EXPOSE_PORT}
    
  celery_worker:
    depends_on:
      - app
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    image: snapspeak-celery:v1
    env_file:
      - .env
    container_name: snapspeak_celery_worker
    command: celery -A MasterProject worker --loglevel=info
  
  nginx:
    depends_on:
    - app
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: snapspeak-nginx:v1
    container_name: snapspeak_nginx
    env_file:
      - .env
    ports:
      - ${NGINX_PROD_PORT}:${NGINX_EXPOSE_PORT}
    volumes:
      - staticfiles_vol:/django/staticfiles

volumes:
  mongo_data:
  staticfiles_vol:
