FROM python:3.10.13-slim

ENV PYTHONBUFFERED=1

WORKDIR /django

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y tesseract-ocr

COPY . .

RUN python manage.py collectstatic --noinput

CMD gunicorn MasterProject.wsgi:application --bind 0.0.0.0:8000

EXPOSE 8000